CarStore.Presentation/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarStore.Presentation.Models
{
    public class CarViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public float Engine { get; set; }
        public int MaxSpeed { get; set; }
        public DateTime ManufactureDate { get; set; }
    }
}

CarStore.Presentation/Models/FullCarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarStore.Presentation.Models
{
    public class FullCarViewModel
    {
        public Guid Id { get; set; }
        public bool InStock { get; set; }
        [Required]
        public string Name { get; set; }
        [Range(0.5, 7)]
        public float Engine { get; set; }
        public int MaxSpeed { get; set; }
        [MaxLength(256)]
        public string Description { get; set; }
        public DateTime ManufactureDate { get; set; }

    }
}

CarStore.Presentation/Models/LocalizationVewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarStore.Presentation.Models
{
    public class LocalizationVewModel
    {
        public string LocalizationId { get; set; }
        public string Name { get; set; }
    }
}

CarStore.Presentation/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarStore.Presentation.Models
{
    public class LoginViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

CarStore.Presentation/Models/UserViewModel.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarStore.Presentation.Models
{
    public class UserViewModel : IUser<string>
    {
        public string Id { get; set; }
        public string UserName { get; set; }
    }
}

CarStore.Presentation/Controllers/AdministrationController.cs
using CarStore.Business.Models;
using CarStore.Business.Repositories;
using CarStore.Business.Services;
using CarStore.Presentation.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarStore.Presentation.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly ICarRepository _carRepository;

        public AdministrationController(ICarRepository carRepository)
        {
            _carRepository = carRepository;
        }

        public ActionResult Index()
        {
            var cars = _carRepository
                .GetAllCars()
                .Select(c => new CarViewModel
                {
                    Id = c.Id,
                    Engine = c.Engine,
                    MaxSpeed = c.MaxSpeed,
                    Name = c.Name
                });

            return View(cars);
        }

        public ActionResult Edit(Guid id)
        {
            var car = _carRepository.GetCarById(id);
            var vm = new FullCarViewModel
            {
                Description = car.Description,
                Engine = car.Engine,
                Id = car.Id,
                InStock = car.InStock,
                MaxSpeed = car.MaxSpeed,
                Name = car.Name,
                ManufactureDate = car.ManufactureDate
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FullCarViewModel car)
        {
            if (!ModelState.IsValid) return View(car);

            SaveImage(car);
            var model = new Car
            {
                Id = car.Id,
                Description = car.Description,
                Engine = car.Engine,
                InStock = car.InStock,
                MaxSpeed = car.MaxSpeed,
                ManufactureDate = car.ManufactureDate,
                Name = car.Name
            };
            _carRepository.UpdateCar(model);

            return RedirectToAction("Index");
        }

        private void SaveImage(FullCarViewModel car)
        {
            if (Request.Files.Count == 0) return;

            var file = Request.Files[0];
            if (file.ContentLength == 0) return;

            var fileExtention = Path.GetExtension(file.FileName);

            var path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/App_Data/Images/"), $"{car.Id}.{fileExtention}");
            file.SaveAs(path);
        }
    }
}

CarStore.Presentation/Controllers/CarsController.cs
using CarStore.Business.Repositories;
using CarStore.Business.Services;
using CarStore.Presentation.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarStore.Presentation.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarService _carService;
        private readonly ICarRepository _carRepository;

        public CarsController(ICarRepository carRepository, ICarService carService)
        {
            _carRepository = carRepository;
            _carService = carService;
        }

        public ActionResult Index()
        {
            var cars = _carService
                .GetAvaliableCars()
                .Select(c => new CarViewModel
                {
                    Id = c.Id,
                    Engine = c.Engine,
                    MaxSpeed = c.MaxSpeed,
                    Name = c.Name
                });

            return View(cars);
        }

        public ActionResult Details(Guid id)
        {
            var car = _carRepository.GetCarById(id);
            var vm = new FullCarViewModel
            {
                Description = car.Description,
                Engine = car.Engine,
                Id = car.Id,
                InStock = car.InStock,
                MaxSpeed = car.MaxSpeed,
                Name = car.Name
            };

            return View(vm);
        }

        public ActionResult Photo(Guid id)
        {
            var path = System.Web.HttpContext.Current.Server.MapPath("~/App_Data/Images/");
            var file = Directory.GetFiles(path, $"{id}.*").FirstOrDefault();

            if (string.IsNullOrEmpty(file)) throw new HttpException(404, "File not found");

            return File(Path.Combine(path, file), $"image/{Path.GetExtension(file)}");

        }
    }
}

CarStore.Presentation/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CarStore.Presentation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string temp)
        {
            return View();
        }
    }
}

CarStore.Presentation/Controllers/LoginController.cs
using CarStore.Presentation.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;

namespace CarStore.Presentation.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserManager<UserViewModel, string> _userManager;

        protected IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        public LoginController(UserManager<UserViewModel, string> userManager)
        {
            _userManager = userManager;
        }

        public ActionResult Login()
        {
            return PartialView(new LoginViewModel());
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel login)
        {

            var user = await _userManager.FindAsync(login.UserName, login.Password);
            if (user == null)
            {
                return View();
            }

            var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
            AuthenticationManager.SignIn(identity);

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult Logout()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Unauthorized(string returnUrl)
        {
            return View();
        }
    }
}

CarStore.Presentation/Views/Administration/Edit.cshtml
@model CarStore.Presentation.Models.FullCarViewModel

@{
    ViewBag.Title = "Edit -" + Model.Name;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Edit - @Html.DisplayFor(car => car.Name)</h3>
    </div>
    <div class="panel-body">
        <div class="container-fluid">@Html.ValidationSummary()</div>
        @using (Html.BeginForm("Edit", "Administration", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(car => car.Id)
            <div class="form-group">
                @Html.LabelFor(car => car.Name, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.TextBoxFor(car => car.Name, new { @class = "form-control" })
                    <div>
                        @Html.ValidationMessageFor(car => car.Name)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(car => car.Engine, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.TextBoxFor(car => car.Engine, new { @class = "form-control" })
                    <div>
                        @Html.ValidationMessageFor(car => car.Engine)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(car => car.MaxSpeed, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.TextBoxFor(car => car.MaxSpeed, new { @class = "form-control" })
                    <div>
                        @Html.ValidationMessageFor(car => car.MaxSpeed)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(car => car.ManufactureDate, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.DatepickerFor(car => car.ManufactureDate, new { @class = "form-control" })
                    <div>
                        @Html.ValidationMessageFor(car => car.ManufactureDate)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(car => car.Description, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.TextAreaFor(car => car.Description, new { @class = "form-control", rows = "3" })
                    <div>
                        @Html.ValidationMessageFor(car => car.Description)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="image" class="col-xs-2 control-label"></label>
                <div class="col-xs-10">
                    <input name="image" type="file" />
                    <p class="help-block">Pick up a photo.</p>
                    <div>
                        @Html.ValidationMessageFor(car => car.Description)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <div class="checkbox">
                        <label>
                            @Html.CheckBoxFor(car => car.InStock) In stock
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>

CarStore.Presentation/Views/Administration/Index.cshtml
@model IEnumerable<CarStore.Presentation.Models.CarViewModel>

@{
    ViewBag.Title = "Edit Cars";
}

<h4>The following cars could be edited:</h4>
<table class="table table-responsive table-hover table-condensed">
    <thead>
        <tr>
            <th>Name</th>
            <th>Engine</th>
            <th>Max Speed</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(c => car.Name)
                </td>
                <td>
                    @Html.DisplayFor(c => car.Engine) L
                </td>
                <td>
                    @Html.DisplayFor(c => car.MaxSpeed) km/h
                </td>
                <th>
                    @Html.ActionLink("Edit", "Edit", "Administration", new { id = car.Id }, new { @class = "btn btn-default btn-sm" })
                </th>
            </tr>
        }
    </tbody>
</table>

CarStore.Presentation/Views/Cars/Details.cshtml
@model CarStore.Presentation.Models.FullCarViewModel

@{
    ViewBag.Title = "Details - " + Model.Name;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Html.DisplayFor(car => car.Name)</h3>
    </div>
    <div class="panel-body">
        <div class="text-center">
            <img src="@Url.Action("Photo", "Cars", new { id = Model.Id })" width="500" height="500" class="img-thumbnail" />
        </div>
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(car => car.Engine):</strong> @Html.DisplayFor(car => car.Engine)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(car => car.MaxSpeed):</strong> @Html.DisplayFor(car => car.MaxSpeed) @MyHelpers.Speed()
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(car => car.Description):</strong><br />@Html.DisplayFor(car => car.Description)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(car => car.ManufactureDate):</strong><br />@Html.DisplayFor(car => car.ManufactureDate)
                </div>
            </div>
        </div>
    </div>
</div>

CarStore.Presentation/Views/Cars/Index.cshtml
@model IEnumerable<CarStore.Presentation.Models.CarViewModel>

@{
    ViewBag.Title = "Cars";
}

<h4>The following cars are in the stock:</h4>
<table class="table table-responsive table-hover table-condensed">
    <thead>
        <tr>
            <th>Name</th>
            <th>Engine</th>
            <th>Max Speed</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(c => car.Name)
                </td>
                <td>
                    @Html.DisplayFor(c => car.Engine) L
                </td>
                <td>
                    @Html.DisplayFor(c => car.MaxSpeed) km/h
                </td>
                <th>
                    @Html.ActionLink("Details", "Details", "Cars", new { id = car.Id }, new { @class = "btn btn-default btn-sm" })
                </th>
            </tr>
        }
    </tbody>
</table>

CarStore.Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

@section SubHeader
{
    <div class="jumbotron">
        <h2 class="text-center text-uppercase text-primary">@Resource.Text_WelcomeMessage</h2>
    </div>
}

CarStore.Presentation/Views/Login/Login.cshtml
@model CarStore.Presentation.Models.LoginViewModel

@if (User != null && !User.Identity.IsAuthenticated)
{
    using (Html.BeginForm("Login", "Login", FormMethod.Post, new { @class = "navbar-form navbar-right" }))
    {
        <div class="form-group">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder = "User Name" })
        </div>
        <div class="form-group">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })

        </div>
        <button type="submit" class="btn btn-default">Log in</button>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello, <u>@User.Identity.Name</u> <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
            </ul>
        </li>
    </ul>
}

CarStore.Presentation/Views/Login/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
}

<h3 class="text-danger">Unauthorized access!</h3>

CarStore.Presentation/Views/Shared/_Language.cshtml
@using System.Threading
@using (Html.BeginForm("SetLocalization", "Localization", FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.DropDownList("localizationId", LocalizationHelper.GetAvaliableLocalizations()
        .Select(l =>
        {
            var routeValues = new RouteValueDictionary(Url.RequestContext.RouteData.Values);
            if (!routeValues.ContainsKey("lang"))
            {
                routeValues.Add("lang", l.LocalizationId);
            }
            else
            {
                routeValues["lang"] = l.LocalizationId;
            }

            var item = new SelectListItem
            {
                Text = l.Name,
                //Value = l.LocalizationId,
                Value = Url.Action((string)Url.RequestContext.RouteData.Values["action"], routeValues),
                Selected = Thread.CurrentThread.CurrentUICulture.Name.Equals(l.LocalizationId)
            };
            return item;
        }), Resource.Text_ChooseLanguage, new { @class = "form-control" })
}

CarStore.Presentation/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    var claimsIdentity = User.Identity as ClaimsIdentity;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cars", "Index", "Cars")</li>
                    @if (User != null && User.Identity.IsAuthenticated && claimsIdentity.HasClaim(ClaimTypes.Role, "Admin"))
                    {
                        <li>@Html.ActionLink("Administration", "Index", "Administration")</li>
                    }
                </ul>
                @Html.Action("Login", "Login")
            </div>
        </div>

    </div>

    <div class="container body-content">
        @RenderSection("SubHeader", false)
        <div class="container-fluid top-buffer">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            <div class="pull-right">@Html.Partial("_Language")</div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/bootstrap-datepicker.min.js"></script>
    <script src="~/scripts/bootstrap-datepicker-globalize.js"></script>
    <script src="~/scripts/app.js"></script>
</body>
</html>